name: CI

on: [push]

jobs:
  abaplint:
    runs-on: buntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: abaplint
      uses: abaplint/actions-abaplint@main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          echo test, and deploy your project.
